### ISSUE TITLE
Incorrect size for packages with the same name as Node core modules

### ISSUE THREAD

**Issue by goto-bus-stop** [pastelsky/package-build-stats#1]
Eg: https://bundlephobia.com/result?p=util@0.11.0
![image](https://user-images.githubusercontent.com/1006268/42472451-a5991860-83c1-11e8-8c3c-a2d5dcdd5620.png)

The generated entry point does `require('util')` which I guess turns into an external require() call because of this?
https://github.com/pastelsky/package-build-stats/blob/9aeb7a6ea98cb3a6a158a8af92a894ba91e1aa2d/src/getPackageStats.js#L111-L114

One kind of hacky way to work around this could be to append a / to the generated require() call—that'll force the resolution algorithm to use the dependency from node_modules rather than the builtin.

**Comment by pastelsky** [comment]
In my opinion, it is best to avoid keeping names of packages to be similar to internal node packages. The npm documentation makes this clear –
 https://docs.npmjs.com/files/package.json

 There is a way to avoid this, and I'm willing to accept a PR to filter out name of the package from these externals, but this isn't something I'm actively looking to fix.
