### ISSUE TITLE
`package-lock.json` warning appears when using Yarn

### ISSUE THREAD

**Issue by Calinou** [pastelsky/package-build-stats#18]
```text
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

We should settle on using either npm or Yarn to manage packages, not both :slightly_smiling_face: 

I'd vote for Yarn personally as the [main Bundlephobia repository](https://github.com/pastelsky/bundlephobia) also uses Yarn.

**Comment by pastelsky** [comment]
Yeah, I probably committed that inadvertently. Thanks for reporting it — has been removed now.
