### ISSUE TITLE
ERROR in main.bundle.js from Terser "Export" statement may only appear at the top level

### ISSUE THREAD

**Issue by HackbrettXXX** [pastelsky/package-build-stats#26]
This error occurs when the browser/module/main file of a package contains es6 style `import`/`export` statements.

Example where the error occurs: https://bundlephobia.com/result?p=jspdf@2.1.1
Related issues: https://github.com/pastelsky/bundlephobia/issues/164, https://github.com/pastelsky/bundlephobia/issues/383

Modern libraries usually provide bundles with all es5 code except for import/export statements. This allows for optimal tooling support (treeshaking, etc.). Bundlephobia should support these kinds of libraries.

The reason for this error is that files that match this regex `/\.min\.js$/` are not processed by webpack and thus the import/export statements are not replaced by webpack imports/exports.

The fix would be to remove the `noParse` rule from the webpack config. See https://github.com/pastelsky/package-build-stats/blame/master/src/webpack.config.js#L92

If you agree, I can prepare a pull request.

**Comment by HackbrettXXX** [comment]
See also the webpack documentation for the `noParse` rule: https://webpack.js.org/configuration/module/#modulenoparse

**Comment by pastelsky** [comment]
The no-parse rule provides a boost to build times for some packages, but its probably not worth keeping around if it breaks packages. 

I'm willing to take a PR for this if you think there are more such packages.

**Comment by HackbrettXXX** [comment]
@pastelsky thanks for your answer. I do think this affects more packages. I created a PR ;)
