### ISSUE TITLE
move node-sass -> sass

### ISSUE THREAD

**Issue by tjx666** [pastelsky/package-build-stats#40]
I often install node-sass 4.14.1 failed when run postinstall script, please move node-sass to sass. node-sass had been deprecated.

**Comment by ivanoats** [comment]
Maintainers, would you accept a PR for this?

**Comment by neo** [comment]
+1 that it has been a real issue

**Comment by ivanoats** [comment]
Opened #50

**Comment by pastelsky** [comment]
Fixed.
